// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9jvyIItwMWPBh6-5aqsUvShLClalAyLE',
    appId: '1:340855687882:web:f81a70b9b1bddb607d4233',
    messagingSenderId: '340855687882',
    projectId: 'fluuterlogin-ae6dd',
    authDomain: 'fluuterlogin-ae6dd.firebaseapp.com',
    storageBucket: 'fluuterlogin-ae6dd.firebasestorage.app',
    measurementId: 'G-31GGZ7W91P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfEV8prTtOTafRCLIIOSMEXtVE-9xmjwo',
    appId: '1:340855687882:android:c38e67ddc0736c1b7d4233',
    messagingSenderId: '340855687882',
    projectId: 'fluuterlogin-ae6dd',
    storageBucket: 'fluuterlogin-ae6dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy1Q0e-d0KLwyn7wB8p0Dfeug7XTynpvY',
    appId: '1:340855687882:ios:162f55d24ed000497d4233',
    messagingSenderId: '340855687882',
    projectId: 'fluuterlogin-ae6dd',
    storageBucket: 'fluuterlogin-ae6dd.firebasestorage.app',
    iosClientId: '340855687882-lvb1eb1ibu0rfmo6e78o8je3o4fs3rjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.warungly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy1Q0e-d0KLwyn7wB8p0Dfeug7XTynpvY',
    appId: '1:340855687882:ios:162f55d24ed000497d4233',
    messagingSenderId: '340855687882',
    projectId: 'fluuterlogin-ae6dd',
    storageBucket: 'fluuterlogin-ae6dd.firebasestorage.app',
    iosClientId: '340855687882-lvb1eb1ibu0rfmo6e78o8je3o4fs3rjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.warungly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9jvyIItwMWPBh6-5aqsUvShLClalAyLE',
    appId: '1:340855687882:web:31900e963a2f826b7d4233',
    messagingSenderId: '340855687882',
    projectId: 'fluuterlogin-ae6dd',
    authDomain: 'fluuterlogin-ae6dd.firebaseapp.com',
    storageBucket: 'fluuterlogin-ae6dd.firebasestorage.app',
    measurementId: 'G-244T8KVLFN',
  );
}
